/* -------------------------------------------------
   1. New normalized table
   ------------------------------------------------- */
CREATE TABLE Accounts (
    AccountID     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MemberID      INTEGER NOT NULL,
    AccountNumber VARCHAR(20) NOT NULL,
    CONSTRAINT FK_Accounts_Members
        FOREIGN KEY (MemberID) REFERENCES Members(MemberID)
);

/* -------------------------------------------------
   2. Migrate data (standard UNION ALL)
   ------------------------------------------------- */
INSERT INTO Accounts (MemberID, AccountNumber)
SELECT MemberID, AccountNumber1 FROM Members WHERE AccountNumber1 IS NOT NULL
UNION ALL
SELECT MemberID, AccountNumber2 FROM Members WHERE AccountNumber2 IS NOT NULL
UNION ALL
SELECT MemberID, AccountNumber3 FROM Members WHERE AccountNumber3 IS NOT NULL;

/* -------------------------------------------------
   3. Clean up the original table
   ------------------------------------------------- */
ALTER TABLE Members DROP COLUMN AccountNumber1
ALTER TABLE Members DROP COLUMN AccountNumber2
ALTER TABLE Members DROP COLUMN AccountNumber3